### ISSUE TITLE
object 'SWEREFID' not found

### ISSUE THREAD

**Issue by qianhuang29** [claudiavonbromssen/Trend-screening#4]
Hi, 

Thanks for sharing the code, which is super useful.

I wanted to reproduce the plots using your code, and I have perhaps a stupid question here. While I ran "Screening_plots_for_article", an error emerged. This error occurred after running this line:

screenmodel_out %>%
  filter(SWEREFID=="6585489-420879", name=="pH")%>%
plot_individual_trend(y = "pH")

It said: "Error in filter(., SWEREFID == "6585489-420879", name == "pH") :ℹ In group 1: `name = "Sulfate"`. Caused by error:! object 'SWEREFID' not found". 

I checked the "screenmodel_out" which was the result of screenmodeling() and I couldn't find the variable 'SWEREFID' there. I don't know if it is related to how the grouping variables are handled inside the screeningmodeling function. Perhaps you have an idea of how to fix this?

Thanks!

Qian

**Comment by claudiavonbromssen** [comment]
Hi
Thanks for highlighting this issue. I have missed a line after updating the source code. The model run was missing the confidence level, which made the model output incorrect. Let me know if you meet any additional problems. 
Claudia
